#ifndef _MINIM_VERSION_H_
#define _MINIM_VERSION_H_

#define MINIM_VERSION_MAJOR     0
#define MINIM_VERSION_MINOR     2
#define MINIM_VERSION_PATCH     1
#define MINIM_VERSION_STR       "0.2.1-dev"

#define MINIM_VERSION_NUM       (MINIM_VERSION_MAJOR << 16 | MINIM_VERSION_MINOR << 8 | MINIM_VERSION_PATCH)

#endif